# basics
model = "google/gemma-2b"
dataset = "mrpc"
# training
training_optimizer = "adamw"
learning_rate = 1e-5
weight_decay = 0.01
max_epochs = 10
batch_size = 1
log_every_n_steps = 20
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
is_pretrained = true
project_dir = "./ags_output"