# basics
model = "opt_lora"
dataset = "alpaca"
load_name = "ags_output/opt_lora_causal_language_modeling_alpaca_2024-02-22/training_ckpts/last_chkpt.ckpt"
load_type = "pl"
backbone_model = "facebook/opt-350m"
resume_training = true
# training
training_optimizer = "adamw"
learning_rate = 2e-4
weight_decay = 0.01
max_epochs = 20
batch_size = 4
log_every_n_steps = 20
# torch lightning
task = "causal_language_modeling"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = false
project_dir = "./ags_output"
lora_config = "./configs/lora/lora_networkwise.toml"
