# basics
model = "facebook/opt-125m"
dataset = "mrpc"
# training
training_optimizer = "adamw"
#learning_rate = 1e-6
weight_decay = 0.01
#lr_scheduler = "cosine_annealing"
#eta_min = 1e-7
max_epochs = 10
batch_size = 32
log_every_n_steps = 10
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 1
#accelerator = "cpu"
is_pretrained = true
project_dir = "./ags_output"