total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 1
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 72
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 87
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 79
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 87
residual_1 = 0
residual_2 = 50
shortcut_sa = 72
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 3
shortcut_sa = 42
shortcut_ffn = 0

[layer_10]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 64
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 1

[layer_16]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 3
shortcut_sa = 99
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 5
shortcut_sa = 1
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 4
shortcut_sa = 99
shortcut_ffn = 100

[layer_19]
q_proj = 0
v_proj = 100
residual_1 = 3
residual_2 = 10
shortcut_sa = 100
shortcut_ffn = 3

[layer_20]
q_proj = 0
v_proj = 99
residual_1 = 8
residual_2 = 95
shortcut_sa = 100
shortcut_ffn = 100

[layer_21]
q_proj = 0
v_proj = 100
residual_1 = 3
residual_2 = 53
shortcut_sa = 91
shortcut_ffn = 54

[layer_22]
q_proj = 0
v_proj = 23
residual_1 = 4
residual_2 = 98
shortcut_sa = 99
shortcut_ffn = 31

[layer_23]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 2
shortcut_sa = 28
shortcut_ffn = 25
