total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 37
residual_1 = 43
residual_2 = 42
shortcut_sa = 0

[layer_1]
q_proj = 18
v_proj = 95
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 85
residual_1 = 0
residual_2 = 0
shortcut_sa = 42
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 96
residual_1 = 6
residual_2 = 0
shortcut_sa = 38
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 96
residual_1 = 0
residual_2 = 0
shortcut_sa = 14
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 98
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 96
residual_1 = 1
residual_2 = 80
shortcut_sa = 57
shortcut_ffn = 0

[layer_10]
q_proj = 85
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 75
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 2
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 1

[layer_16]
q_proj = 0
v_proj = 100
residual_1 = 4
residual_2 = 1
shortcut_sa = 100
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 100
residual_1 = 2
residual_2 = 2
shortcut_sa = 100
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 2
shortcut_sa = 100
shortcut_ffn = 1

[layer_19]
q_proj = 0
v_proj = 100
residual_1 = 3
residual_2 = 63
shortcut_sa = 100
shortcut_ffn = 5

[layer_20]
q_proj = 0
v_proj = 100
residual_1 = 42
residual_2 = 13
shortcut_sa = 54
shortcut_ffn = 12

[layer_21]
q_proj = 0
v_proj = 89
residual_1 = 2
residual_2 = 2
shortcut_sa = 47
shortcut_ffn = 6

[layer_22]
q_proj = 0
v_proj = 54
residual_1 = 21
residual_2 = 2
shortcut_sa = 96
shortcut_ffn = 66

[layer_23]
q_proj = 0
v_proj = 83
residual_1 = 2
residual_2 = 1
shortcut_sa = 22
shortcut_ffn = 3
