total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 89
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 84
residual_1 = 0
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 90
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 88
residual_1 = 0
residual_2 = 0
shortcut_sa = 46
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 86
residual_1 = 1
residual_2 = 28
shortcut_sa = 1
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 94
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 2

[layer_8]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 2
shortcut_sa = 64
shortcut_ffn = 0

[layer_10]
q_proj = 9
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 30
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 30
shortcut_ffn = 0

[layer_12]
q_proj = 35
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 98
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 1
shortcut_sa = 4
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 100
residual_1 = 100
residual_2 = 6
shortcut_sa = 100
shortcut_ffn = 2

[layer_18]
q_proj = 0
v_proj = 100
residual_1 = 2
residual_2 = 3
shortcut_sa = 7
shortcut_ffn = 5

[layer_19]
q_proj = 0
v_proj = 100
residual_1 = 3
residual_2 = 6
shortcut_sa = 99
shortcut_ffn = 1

[layer_20]
q_proj = 0
v_proj = 99
residual_1 = 2
residual_2 = 98
shortcut_sa = 89
shortcut_ffn = 13

[layer_21]
q_proj = 0
v_proj = 99
residual_1 = 59
residual_2 = 84
shortcut_sa = 98
shortcut_ffn = 48

[layer_22]
q_proj = 0
v_proj = 99
residual_1 = 12
residual_2 = 4
shortcut_sa = 74
shortcut_ffn = 66

[layer_23]
q_proj = 0
v_proj = 91
residual_1 = 2
residual_2 = 13
shortcut_sa = 17
shortcut_ffn = 32
