total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 17
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 31
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 27
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 41
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 44
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 43
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 44
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 43
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_10]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 50
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 31

[layer_17]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 0
shortcut_sa = 50
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 4

[layer_19]
q_proj = 0
v_proj = 50
residual_1 = 4
residual_2 = 4
shortcut_sa = 48
shortcut_ffn = 3

[layer_20]
q_proj = 0
v_proj = 50
residual_1 = 50
residual_2 = 49
shortcut_sa = 50
shortcut_ffn = 50

[layer_21]
q_proj = 0
v_proj = 50
residual_1 = 35
residual_2 = 15
shortcut_sa = 50
shortcut_ffn = 50

[layer_22]
q_proj = 0
v_proj = 50
residual_1 = 5
residual_2 = 49
shortcut_sa = 50
shortcut_ffn = 48

[layer_23]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 9
shortcut_sa = 23
shortcut_ffn = 20
