total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 26
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 45
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 46
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 48
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 21
shortcut_sa = 25
shortcut_ffn = 0

[layer_10]
q_proj = 23
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 1

[layer_16]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 1
shortcut_sa = 43
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 1
shortcut_sa = 50
shortcut_ffn = 3

[layer_18]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 2

[layer_19]
q_proj = 0
v_proj = 50
residual_1 = 3
residual_2 = 2
shortcut_sa = 50
shortcut_ffn = 2

[layer_20]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 14
shortcut_sa = 50
shortcut_ffn = 50

[layer_21]
q_proj = 0
v_proj = 50
residual_1 = 47
residual_2 = 9
shortcut_sa = 50
shortcut_ffn = 50

[layer_22]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 27
shortcut_sa = 50
shortcut_ffn = 50

[layer_23]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 10
shortcut_sa = 23
shortcut_ffn = 25
