total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 39
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 42
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 34
residual_1 = 0
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 40
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 38
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 36
residual_1 = 1
residual_2 = 2
shortcut_sa = 1
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 44
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 2

[layer_8]
q_proj = 0
v_proj = 42
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 43
residual_1 = 0
residual_2 = 0
shortcut_sa = 14
shortcut_ffn = 0

[layer_10]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 48
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 1
shortcut_sa = 4
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 50
residual_1 = 50
residual_2 = 6
shortcut_sa = 50
shortcut_ffn = 2

[layer_18]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 3
shortcut_sa = 7
shortcut_ffn = 5

[layer_19]
q_proj = 0
v_proj = 50
residual_1 = 3
residual_2 = 6
shortcut_sa = 49
shortcut_ffn = 1

[layer_20]
q_proj = 0
v_proj = 49
residual_1 = 2
residual_2 = 49
shortcut_sa = 50
shortcut_ffn = 13

[layer_21]
q_proj = 0
v_proj = 50
residual_1 = 46
residual_2 = 49
shortcut_sa = 48
shortcut_ffn = 42

[layer_22]
q_proj = 0
v_proj = 50
residual_1 = 12
residual_2 = 4
shortcut_sa = 49
shortcut_ffn = 49

[layer_23]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 13
shortcut_sa = 17
shortcut_ffn = 32
