total_reallocation_number = 80

[layer_0]
q_proj = 9
v_proj = 74
residual_1 = 35
residual_2 = 1
shortcut_sa = 6

[layer_1]
q_proj = 56
v_proj = 75
residual_1 = 69
residual_2 = 76
shortcut_sa = 76
shortcut_ffn = 2

[layer_2]
q_proj = 2
v_proj = 67
residual_1 = 69
residual_2 = 72
shortcut_sa = 76
shortcut_ffn = 2

[layer_3]
q_proj = 13
v_proj = 72
residual_1 = 70
residual_2 = 0
shortcut_sa = 76
shortcut_ffn = 12

[layer_4]
q_proj = 1
v_proj = 68
residual_1 = 2
residual_2 = 4
shortcut_sa = 75
shortcut_ffn = 3

[layer_5]
q_proj = 2
v_proj = 74
residual_1 = 3
residual_2 = 4
shortcut_sa = 76
shortcut_ffn = 2

[layer_6]
q_proj = 4
v_proj = 67
residual_1 = 2
residual_2 = 3
shortcut_sa = 8
shortcut_ffn = 3

[layer_7]
q_proj = 7
v_proj = 5
residual_1 = 3
residual_2 = 5
shortcut_sa = 2
shortcut_ffn = 3

[layer_8]
q_proj = 2
v_proj = 2
residual_1 = 8
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 2

[layer_9]
q_proj = 2
v_proj = 3
residual_1 = 3
residual_2 = 7
shortcut_sa = 3
shortcut_ffn = 4

[layer_10]
q_proj = 4
v_proj = 5
residual_1 = 5
residual_2 = 3
shortcut_sa = 5
shortcut_ffn = 2

[layer_11]
q_proj = 3
v_proj = 3
residual_1 = 2
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 0

[layer_12]
q_proj = 5
v_proj = 9
residual_1 = 5
residual_2 = 3
shortcut_sa = 3
shortcut_ffn = 3

[layer_13]
q_proj = 0
v_proj = 6
residual_1 = 2
residual_2 = 4
shortcut_sa = 3
shortcut_ffn = 3

[layer_14]
q_proj = 7
v_proj = 76
residual_1 = 4
residual_2 = 23
shortcut_sa = 6
shortcut_ffn = 4

[layer_15]
q_proj = 5
v_proj = 74
residual_1 = 2
residual_2 = 2
shortcut_sa = 44
shortcut_ffn = 6

[layer_16]
q_proj = 1
v_proj = 76
residual_1 = 3
residual_2 = 2
shortcut_sa = 74
shortcut_ffn = 6

[layer_17]
q_proj = 3
v_proj = 74
residual_1 = 6
residual_2 = 77
shortcut_sa = 72
shortcut_ffn = 7

[layer_18]
q_proj = 3
v_proj = 76
residual_1 = 3
residual_2 = 3
shortcut_sa = 75
shortcut_ffn = 2

[layer_19]
q_proj = 3
v_proj = 74
residual_1 = 2
residual_2 = 2
shortcut_sa = 73
shortcut_ffn = 0

[layer_20]
q_proj = 1
v_proj = 75
residual_1 = 3
residual_2 = 4
shortcut_sa = 41
shortcut_ffn = 78

[layer_21]
q_proj = 11
v_proj = 73
residual_1 = 76
residual_2 = 1
shortcut_sa = 8
shortcut_ffn = 77

[layer_22]
q_proj = 7
v_proj = 71
residual_1 = 4
residual_2 = 6
shortcut_sa = 72
shortcut_ffn = 1

[layer_23]
q_proj = 4
v_proj = 76
residual_1 = 5
residual_2 = 4
shortcut_sa = 71
shortcut_ffn = 2

[layer_24]
q_proj = 74
v_proj = 75
residual_1 = 0
residual_2 = 9
shortcut_sa = 76
shortcut_ffn = 2

[layer_25]
q_proj = 74
v_proj = 77
residual_1 = 2
residual_2 = 2
shortcut_sa = 3
shortcut_ffn = 2

[layer_26]
q_proj = 77
v_proj = 76
residual_1 = 12
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 5

[layer_27]
q_proj = 77
v_proj = 76
residual_1 = 75
residual_2 = 2
shortcut_sa = 5
shortcut_ffn = 4

[layer_28]
q_proj = 75
v_proj = 55
residual_1 = 76
residual_2 = 1
shortcut_sa = 77
shortcut_ffn = 5

[layer_29]
q_proj = 1
v_proj = 76
residual_1 = 3
residual_2 = 4
shortcut_sa = 5
shortcut_ffn = 7

[layer_30]
q_proj = 73
v_proj = 75
residual_1 = 4
residual_2 = 74
shortcut_sa = 78
shortcut_ffn = 3

[layer_31]
q_proj = 3
v_proj = 75
residual_1 = 4
residual_2 = 76
shortcut_sa = 78
shortcut_ffn = 2
