total_reallocation_number = 40

[layer_0]
q_proj = 16
v_proj = 34
residual_1 = 16
residual_2 = 16
shortcut_sa = 6

[layer_1]
q_proj = 20
v_proj = 35
residual_1 = 25
residual_2 = 32
shortcut_sa = 27
shortcut_ffn = 7

[layer_2]
q_proj = 2
v_proj = 21
residual_1 = 24
residual_2 = 8
shortcut_sa = 36
shortcut_ffn = 12

[layer_3]
q_proj = 15
v_proj = 29
residual_1 = 7
residual_2 = 0
shortcut_sa = 34
shortcut_ffn = 7

[layer_4]
q_proj = 1
v_proj = 4
residual_1 = 6
residual_2 = 8
shortcut_sa = 34
shortcut_ffn = 3

[layer_5]
q_proj = 2
v_proj = 31
residual_1 = 5
residual_2 = 3
shortcut_sa = 36
shortcut_ffn = 2

[layer_6]
q_proj = 3
v_proj = 5
residual_1 = 2
residual_2 = 10
shortcut_sa = 4
shortcut_ffn = 3

[layer_7]
q_proj = 4
v_proj = 19
residual_1 = 3
residual_2 = 6
shortcut_sa = 2
shortcut_ffn = 3

[layer_8]
q_proj = 2
v_proj = 2
residual_1 = 35
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 2

[layer_9]
q_proj = 1
v_proj = 9
residual_1 = 3
residual_2 = 10
shortcut_sa = 3
shortcut_ffn = 5

[layer_10]
q_proj = 3
v_proj = 3
residual_1 = 4
residual_2 = 3
shortcut_sa = 6
shortcut_ffn = 2

[layer_11]
q_proj = 2
v_proj = 7
residual_1 = 2
residual_2 = 4
shortcut_sa = 2
shortcut_ffn = 0

[layer_12]
q_proj = 4
v_proj = 7
residual_1 = 4
residual_2 = 3
shortcut_sa = 3
shortcut_ffn = 3

[layer_13]
q_proj = 0
v_proj = 13
residual_1 = 2
residual_2 = 3
shortcut_sa = 7
shortcut_ffn = 3

[layer_14]
q_proj = 6
v_proj = 36
residual_1 = 8
residual_2 = 36
shortcut_sa = 7
shortcut_ffn = 4

[layer_15]
q_proj = 4
v_proj = 25
residual_1 = 2
residual_2 = 4
shortcut_sa = 32
shortcut_ffn = 16

[layer_16]
q_proj = 1
v_proj = 36
residual_1 = 4
residual_2 = 2
shortcut_sa = 35
shortcut_ffn = 6

[layer_17]
q_proj = 3
v_proj = 33
residual_1 = 7
residual_2 = 35
shortcut_sa = 11
shortcut_ffn = 15

[layer_18]
q_proj = 2
v_proj = 36
residual_1 = 9
residual_2 = 5
shortcut_sa = 35
shortcut_ffn = 2

[layer_19]
q_proj = 2
v_proj = 34
residual_1 = 4
residual_2 = 3
shortcut_sa = 36
shortcut_ffn = 1

[layer_20]
q_proj = 1
v_proj = 35
residual_1 = 3
residual_2 = 4
shortcut_sa = 34
shortcut_ffn = 38

[layer_21]
q_proj = 3
v_proj = 34
residual_1 = 8
residual_2 = 2
shortcut_sa = 6
shortcut_ffn = 37

[layer_22]
q_proj = 4
v_proj = 20
residual_1 = 3
residual_2 = 6
shortcut_sa = 35
shortcut_ffn = 1

[layer_23]
q_proj = 1
v_proj = 36
residual_1 = 4
residual_2 = 4
shortcut_sa = 35
shortcut_ffn = 4

[layer_24]
q_proj = 5
v_proj = 34
residual_1 = 1
residual_2 = 26
shortcut_sa = 36
shortcut_ffn = 2

[layer_25]
q_proj = 4
v_proj = 37
residual_1 = 2
residual_2 = 3
shortcut_sa = 3
shortcut_ffn = 3

[layer_26]
q_proj = 35
v_proj = 36
residual_1 = 36
residual_2 = 3
shortcut_sa = 3
shortcut_ffn = 5

[layer_27]
q_proj = 36
v_proj = 36
residual_1 = 13
residual_2 = 3
shortcut_sa = 5
shortcut_ffn = 3

[layer_28]
q_proj = 24
v_proj = 10
residual_1 = 36
residual_2 = 1
shortcut_sa = 37
shortcut_ffn = 4

[layer_29]
q_proj = 10
v_proj = 36
residual_1 = 4
residual_2 = 12
shortcut_sa = 9
shortcut_ffn = 7

[layer_30]
q_proj = 26
v_proj = 35
residual_1 = 8
residual_2 = 27
shortcut_sa = 36
shortcut_ffn = 6

[layer_31]
q_proj = 23
v_proj = 34
residual_1 = 7
residual_2 = 8
shortcut_sa = 34
shortcut_ffn = 27
