total_reallocation_number = 20

[layer_0]
q_proj = 7
v_proj = 14
residual_1 = 10
residual_2 = 1
shortcut_sa = 5

[layer_1]
q_proj = 8
v_proj = 15
residual_1 = 9
residual_2 = 16
shortcut_sa = 16
shortcut_ffn = 2

[layer_2]
q_proj = 2
v_proj = 7
residual_1 = 9
residual_2 = 12
shortcut_sa = 16
shortcut_ffn = 2

[layer_3]
q_proj = 9
v_proj = 12
residual_1 = 10
residual_2 = 0
shortcut_sa = 16
shortcut_ffn = 7

[layer_4]
q_proj = 1
v_proj = 8
residual_1 = 2
residual_2 = 3
shortcut_sa = 15
shortcut_ffn = 3

[layer_5]
q_proj = 2
v_proj = 14
residual_1 = 3
residual_2 = 3
shortcut_sa = 16
shortcut_ffn = 2

[layer_6]
q_proj = 4
v_proj = 7
residual_1 = 2
residual_2 = 3
shortcut_sa = 7
shortcut_ffn = 3

[layer_7]
q_proj = 6
v_proj = 3
residual_1 = 3
residual_2 = 5
shortcut_sa = 2
shortcut_ffn = 2

[layer_8]
q_proj = 2
v_proj = 1
residual_1 = 6
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 2

[layer_9]
q_proj = 1
v_proj = 2
residual_1 = 2
residual_2 = 6
shortcut_sa = 3
shortcut_ffn = 4

[layer_10]
q_proj = 3
v_proj = 4
residual_1 = 4
residual_2 = 3
shortcut_sa = 4
shortcut_ffn = 2

[layer_11]
q_proj = 2
v_proj = 2
residual_1 = 2
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 0

[layer_12]
q_proj = 4
v_proj = 5
residual_1 = 4
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 3

[layer_13]
q_proj = 0
v_proj = 4
residual_1 = 1
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 3

[layer_14]
q_proj = 6
v_proj = 16
residual_1 = 3
residual_2 = 14
shortcut_sa = 5
shortcut_ffn = 4

[layer_15]
q_proj = 4
v_proj = 14
residual_1 = 1
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 5

[layer_16]
q_proj = 1
v_proj = 16
residual_1 = 2
residual_2 = 1
shortcut_sa = 14
shortcut_ffn = 6

[layer_17]
q_proj = 3
v_proj = 14
residual_1 = 5
residual_2 = 17
shortcut_sa = 12
shortcut_ffn = 6

[layer_18]
q_proj = 2
v_proj = 16
residual_1 = 2
residual_2 = 3
shortcut_sa = 15
shortcut_ffn = 2

[layer_19]
q_proj = 2
v_proj = 14
residual_1 = 2
residual_2 = 1
shortcut_sa = 13
shortcut_ffn = 0

[layer_20]
q_proj = 1
v_proj = 15
residual_1 = 2
residual_2 = 3
shortcut_sa = 3
shortcut_ffn = 18

[layer_21]
q_proj = 7
v_proj = 13
residual_1 = 16
residual_2 = 1
shortcut_sa = 5
shortcut_ffn = 17

[layer_22]
q_proj = 5
v_proj = 11
residual_1 = 3
residual_2 = 5
shortcut_sa = 12
shortcut_ffn = 1

[layer_23]
q_proj = 3
v_proj = 16
residual_1 = 4
residual_2 = 3
shortcut_sa = 11
shortcut_ffn = 2

[layer_24]
q_proj = 14
v_proj = 15
residual_1 = 0
residual_2 = 8
shortcut_sa = 16
shortcut_ffn = 2

[layer_25]
q_proj = 14
v_proj = 17
residual_1 = 1
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 2

[layer_26]
q_proj = 17
v_proj = 16
residual_1 = 11
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 5

[layer_27]
q_proj = 17
v_proj = 16
residual_1 = 15
residual_2 = 2
shortcut_sa = 5
shortcut_ffn = 3

[layer_28]
q_proj = 15
v_proj = 4
residual_1 = 16
residual_2 = 1
shortcut_sa = 17
shortcut_ffn = 4

[layer_29]
q_proj = 1
v_proj = 16
residual_1 = 3
residual_2 = 3
shortcut_sa = 4
shortcut_ffn = 6

[layer_30]
q_proj = 13
v_proj = 15
residual_1 = 3
residual_2 = 14
shortcut_sa = 18
shortcut_ffn = 3

[layer_31]
q_proj = 2
v_proj = 15
residual_1 = 3
residual_2 = 16
shortcut_sa = 18
shortcut_ffn = 2
