total_reallocation_number = 40

[layer_0]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40

[layer_1]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_2]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_3]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_4]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_5]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_6]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_7]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_8]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_9]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_10]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_11]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_12]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_13]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_14]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_15]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_16]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_17]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_18]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_19]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_20]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_21]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_22]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_23]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_24]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_25]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_26]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_27]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_28]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_29]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_30]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40

[layer_31]
q_proj = 40
v_proj = 40
residual_1 = 40
residual_2 = 40
shortcut_sa = 40
shortcut_ffn = 40
